### ISSUE TITLE
broken links in vignette

### ISSUE THREAD

**Issue by vjcitn** [HCBravoLab/MicrobiomeExperiment#16]
at https://github.com/HCBravoLab/MicrobiomeExperiment/blob/master/vignettes/MicrobiomeExperiment-basics.Rmd#installation

there are two links given that don't resolve -- one for installation tutorial and
one for http://joey711.github.io/MicrobiomeExperiment/ asserted to be the home
for the package

**Comment by dombraccia** [comment]
Link for the MicrobiomeExoeriment home page is fixed. Installation tutorial link is still down, however.
