### ISSUE TITLE
Rename `tree` slot/argument in MicrobiomeFeatures

### ISSUE THREAD

**Issue by hcorrada** [HCBravoLab/MicrobiomeExperiment#18]
https://github.com/HCBravoLab/MicrobiomeExperiment/blob/e2c76b3e5d7117fad4d65c33b05cb9b71f9a2b62/R/MicrobiomeFeatures-class.R#L8

Rename to `phyloTree`

**Comment by dombraccia** [comment]
Resolved in this commit: 2bb1c7
